### ISSUE TITLE
developers.optimizely.com

### ISSUE THREAD

**Issue by wfalkwallace** [IAmMalte/swift-example-optimizely#1]
Hey @IAmMalte,

We're incorporating many of the tips from your tutorial here into our documentation at developers.optimizely.com (and including a special thanks, linking here and to your profile). I just wanted to send along a heads up and also note that we've added a section on using code blocks in Swift as well. Thanks for the awesome tutorial!

Will + The Optimizely Team

**Comment by IAmMalte** [comment]
Hi Will,

thanks for the message. Looking forward to seeing your documentation as we will integrate Optimizely 
in our own app that we launched today: https://itunes.apple.com/app/id938182547?mt=8 <https://itunes.apple.com/app/id938182547?mt=8>

Best
Malte

**Comment by wfalkwallace** [comment]
Hi Malte,

The documentation is up now for [installation/setup](http://developers.optimizely.com/ios/#(optional)-sdk-setup-with-swift), [live variables](http://developers.optimizely.com/ios/#register-live-variables), and [code blocks](http://developers.optimizely.com/ios/#code-blocks). The app looks great - excited to see what you accomplish with the SDK!

Thanks,
Will
